# Generated by Django 4.2.1 on 2024-12-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0054_control_is_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text='Indique si cette procédure est épinglée', verbose_name='Epinglé'),
        ),
    ]
